kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/pitakill/swiss-knife
steps:
  - name: test
    image: golang
    commands:
      - cd slice
      - go generate
      - go test -race -coverprofile=coverage.txt -covermode=atomic
