version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    steps:
      - checkout
      - run: cd slice && go generate && go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)

